import { useMemo, useState } from "react"
import {
  eachDayOfInterval,
  format,
  startOfDay,
  startOfMonth,
  subDays,
} from "date-fns"
import {
  ArrowDownToLine,
  ArrowUpFromLine,
  CalendarRange,
  ChartColumn,
  ChartPie,
  CircleDollarSign,
  DatabaseZap,
  FolderGit2,
  MessagesSquare,
} from "lucide-react"
import type { DateRange } from "react-day-picker"
import {
  Bar,
  BarChart,
  CartesianGrid,
  ComposedChart,
  Label,
  Line,
  Pie,
  PieChart,
  XAxis,
  YAxis,
} from "recharts"

import { Badge } from "@/shared/ui/badge"
import { Button } from "@/shared/ui/button"
import { Calendar } from "@/shared/ui/calendar"
import {
  ChartContainer,
  ChartLegend,
  ChartLegendContent,
  ChartTooltip,
  ChartTooltipContent,
  type ChartConfig,
} from "@/shared/ui/chart"
import { Popover, PopoverContent, PopoverTrigger } from "@/shared/ui/popover"
import { Tooltip, TooltipContent, TooltipTrigger } from "@/shared/ui/tooltip"
import { cn } from "@/shared/lib/utils"

import type {
  AiUsageByModel,
  AiUsageByWorkspace,
  AiUsageDaily,
  AiUsageRange,
  AiUsageTotals,
} from "../api"
import { useAiUsage } from "../queries"
import { SettingsGroup } from "../components/settings-ui"

// ── Formatting ────────────────────────────────────────────────────────────────

const compactFormat = new Intl.NumberFormat("en-US", {
  notation: "compact",
  maximumFractionDigits: 1,
})
const fullFormat = new Intl.NumberFormat("en-US")

function formatTokens(n: number): string {
  return n >= 10_000 ? compactFormat.format(n) : fullFormat.format(n)
}

function formatCost(n: number): string {
  if (n === 0) return "$0.00"
  if (n < 0.01) return `$${n.toFixed(4)}`
  return `$${n.toFixed(2)}`
}

/** Parse a local-time YYYY-MM-DD day key into a Date. */
function parseDay(day: string): Date {
  return new Date(`${day}T00:00:00`)
}

function formatDayShort(day: string): string {
  return format(parseDay(day), "MMM d")
}

function formatDayFull(day: string): string {
  return format(parseDay(day), "EEE, MMM d, yyyy")
}

const dayKey = (date: Date) => format(date, "yyyy-MM-dd")

// ── Token-type metadata ───────────────────────────────────────────────────────

const TOKEN_TYPES = [
  {
    key: "inputTokens",
    label: "Input",
    color: "bg-chart-1",
    description: "Uncached prompt tokens sent to the model",
  },
  {
    key: "outputTokens",
    label: "Output",
    color: "bg-chart-2",
    description: "Tokens generated by the model",
  },
  {
    key: "cacheReadTokens",
    label: "Cache read",
    color: "bg-chart-3",
    description: "Prompt tokens served from the provider's cache",
  },
  {
    key: "cacheWriteTokens",
    label: "Cache write",
    color: "bg-chart-4",
    description: "Prompt tokens written to the provider's cache",
  },
] as const satisfies readonly {
  key: keyof AiUsageTotals
  label: string
  color: string
  description: string
}[]

// ── Date range selection ──────────────────────────────────────────────────────

/** Active filter: a preset label for display, or null when hand-picked. */
interface RangeSelection {
  label: string | null
  range: AiUsageRange
}

const RANGE_PRESETS: { label: string; range: () => AiUsageRange }[] = [
  { label: "Last 7 days", range: () => ({ days: 7 }) },
  { label: "Last 30 days", range: () => ({ days: 30 }) },
  { label: "Last 90 days", range: () => ({ days: 90 }) },
  {
    label: "This month",
    range: () => {
      const now = new Date()
      return { from: dayKey(startOfMonth(now)), to: dayKey(now) }
    },
  },
  { label: "All time", range: () => ({ days: 0 }) },
]

function selectionTitle(selection: RangeSelection): string {
  if (selection.label) return selection.label
  if ("from" in selection.range) {
    const from = parseDay(selection.range.from)
    const to = parseDay(selection.range.to)
    const sameYear = from.getFullYear() === to.getFullYear()
    return `${format(from, sameYear ? "MMM d" : "MMM d, yyyy")} – ${format(to, "MMM d, yyyy")}`
  }
  return "Custom range"
}

function DateRangePicker({
  selection,
  onChange,
}: {
  selection: RangeSelection
  onChange: (selection: RangeSelection) => void
}) {
  const [open, setOpen] = useState(false)
  const [draft, setDraft] = useState<DateRange | undefined>()

  const selected: DateRange | undefined =
    draft ??
    ("from" in selection.range
      ? {
          from: parseDay(selection.range.from),
          to: parseDay(selection.range.to),
        }
      : undefined)

  // Two-click selection: the first click anchors the range, the second click
  // commits it (clicking the anchor again commits a single-day range). The
  // library's own range math is ignored — its first click already returns a
  // complete from===to range, which would commit immediately. The popover
  // stays open so the result can be inspected and the range refined.
  const handleSelect = (_range: DateRange | undefined, day: Date) => {
    if (!draft?.from) {
      setDraft({ from: day, to: undefined })
      return
    }
    const [from, to] = day < draft.from ? [day, draft.from] : [draft.from, day]
    onChange({ label: null, range: { from: dayKey(from), to: dayKey(to) } })
    setDraft(undefined)
  }

  return (
    <Popover
      open={open}
      onOpenChange={(next) => {
        setOpen(next)
        if (!next) setDraft(undefined)
      }}
    >
      <PopoverTrigger
        render={
          <Button variant="outline">
            <CalendarRange data-icon="inline-start" />
            {selectionTitle(selection)}
          </Button>
        }
      />
      <PopoverContent align="start" className="w-auto gap-0 p-0">
        <div className="flex">
          <div className="flex flex-col gap-0.5 border-r border-border/50 p-2">
            {RANGE_PRESETS.map((preset) => (
              <Button
                key={preset.label}
                variant="ghost"
                size="sm"
                className={cn(
                  "justify-start font-normal",
                  selection.label === preset.label &&
                    "bg-muted font-medium text-foreground"
                )}
                onClick={() => {
                  onChange({ label: preset.label, range: preset.range() })
                  setOpen(false)
                  setDraft(undefined)
                }}
              >
                {preset.label}
              </Button>
            ))}
          </div>
          <Calendar
            mode="range"
            numberOfMonths={2}
            selected={selected}
            onSelect={handleSelect}
            defaultMonth={
              selected?.from ?? startOfMonth(subDays(new Date(), 31))
            }
            disabled={{ after: new Date() }}
            autoFocus
          />
        </div>
      </PopoverContent>
    </Popover>
  )
}

// ── Section ───────────────────────────────────────────────────────────────────

export function UsageSection() {
  const [selection, setSelection] = useState<RangeSelection>({
    label: "Last 30 days",
    range: { days: 30 },
  })
  const { data, isPending, isError } = useAiUsage(selection.range)

  const daily = useMemo(
    () => fillDaily(data?.daily ?? [], selection.range),
    [data?.daily, selection.range]
  )

  return (
    <>
      <div className="flex items-center justify-between gap-2">
        <DateRangePicker selection={selection} onChange={setSelection} />
      </div>

      {isPending ? null : isError ? (
        <p className="py-8 text-center text-sm text-muted-foreground">
          Failed to load usage data. Is the server running?
        </p>
      ) : data.totals.requests === 0 ? (
        <EmptyState />
      ) : (
        <>
          <OverviewCards totals={data.totals} daily={data.daily} />
          <SettingsGroup
            title="Token types"
            description="How the consumed tokens break down by kind."
          >
            <TokenTypeBreakdown totals={data.totals} />
          </SettingsGroup>
          <SettingsGroup
            title="Daily tokens"
            description="Tokens consumed per day, stacked by token type."
          >
            <DailyTokensChart daily={daily} />
          </SettingsGroup>
          <SettingsGroup
            title="Daily cost"
            description="Estimated spend per day, with the running total for the period."
          >
            <DailyCostChart daily={daily} />
          </SettingsGroup>
          <SettingsGroup
            title="Models"
            description="Where the spend goes, and every model used in the selected period."
          >
            <ModelCostChart models={data.byModel} totals={data.totals} />
            <ModelTable models={data.byModel} />
          </SettingsGroup>
          <SettingsGroup
            title="Workspaces"
            description="Usage per workspace, with the models used in each."
          >
            <div className="flex flex-col gap-4 py-3.5">
              {data.byWorkspace.map((ws) => (
                <WorkspaceCard key={ws.workspaceId} workspace={ws} />
              ))}
            </div>
          </SettingsGroup>
        </>
      )}
    </>
  )
}

function EmptyState() {
  return (
    <div className="flex flex-col items-center gap-2 py-16 text-center">
      <ChartColumn className="size-8 text-muted-foreground/50" />
      <p className="text-sm font-medium">No usage recorded</p>
      <p className="max-w-sm text-xs text-muted-foreground">
        No token usage was recorded in the selected period. Usage is recorded
        every time the agent responds — start a conversation in any workspace or
        widen the date range.
      </p>
    </div>
  )
}

// ── Daily series ──────────────────────────────────────────────────────────────

/** Longest gap-filled daily window rendered, to keep all-time charts legible. */
const MAX_CHART_DAYS = 180

const emptyDay = (day: string): AiUsageDaily => ({
  day,
  inputTokens: 0,
  outputTokens: 0,
  cacheReadTokens: 0,
  cacheWriteTokens: 0,
  totalTokens: 0,
  cost: 0,
})

/** Expand sparse daily rows into a contiguous series over the active range. */
function fillDaily(daily: AiUsageDaily[], range: AiUsageRange): AiUsageDaily[] {
  const today = startOfDay(new Date())
  let start: Date
  let end: Date
  if ("from" in range) {
    start = parseDay(range.from)
    end = parseDay(range.to)
  } else if (range.days > 0) {
    start = subDays(today, range.days - 1)
    end = today
  } else {
    if (daily.length === 0) return []
    start = parseDay(daily[0].day)
    end = today
  }
  const minStart = subDays(end, MAX_CHART_DAYS - 1)
  if (start < minStart) start = minStart
  if (end < start) return []

  const byDay = new Map(daily.map((d) => [d.day, d]))
  return eachDayOfInterval({ start, end }).map((date) => {
    const key = dayKey(date)
    return byDay.get(key) ?? emptyDay(key)
  })
}

// ── Overview cards ────────────────────────────────────────────────────────────

function OverviewCards({
  totals,
  daily,
}: {
  totals: AiUsageTotals
  daily: AiUsageDaily[]
}) {
  const promptTokens = totals.inputTokens + totals.cacheReadTokens
  const cacheHitRate =
    promptTokens > 0 ? (totals.cacheReadTokens / promptTokens) * 100 : 0
  const activeDays = daily.filter((d) => d.totalTokens > 0).length

  const cards = [
    {
      label: "Total tokens",
      value: formatTokens(totals.totalTokens),
      detail: `${fullFormat.format(totals.totalTokens)} tokens`,
      icon: ChartColumn,
    },
    {
      label: "Estimated cost",
      value: formatCost(totals.cost),
      detail: "Based on provider list prices",
      icon: CircleDollarSign,
    },
    {
      label: "Requests",
      value: fullFormat.format(totals.requests),
      detail: "LLM responses received",
      icon: MessagesSquare,
    },
    {
      label: "Output tokens",
      value: formatTokens(totals.outputTokens),
      detail: `${fullFormat.format(totals.outputTokens)} generated`,
      icon: ArrowDownToLine,
    },
    {
      label: "Cost per request",
      value: formatCost(
        totals.requests > 0 ? totals.cost / totals.requests : 0
      ),
      detail:
        activeDays > 0
          ? `${formatCost(totals.cost / activeDays)} per active day`
          : "No active days",
      icon: ChartPie,
    },
    {
      label: "Cache hit rate",
      value: `${cacheHitRate.toFixed(1)}%`,
      detail: "Prompt tokens served from cache",
      icon: DatabaseZap,
    },
  ]

  return (
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
      {cards.map((card) => (
        <div
          key={card.label}
          className="flex flex-col gap-1 rounded-lg border border-border/60 p-3"
        >
          <div className="flex items-center gap-1.5 text-muted-foreground">
            <card.icon className="size-3.5" />
            <span className="text-xs">{card.label}</span>
          </div>
          <span className="text-xl font-semibold tracking-tight tabular-nums">
            {card.value}
          </span>
          <span className="truncate text-[11px] text-muted-foreground">
            {card.detail}
          </span>
        </div>
      ))}
    </div>
  )
}

// ── Token type breakdown ──────────────────────────────────────────────────────

function TokenTypeBreakdown({ totals }: { totals: AiUsageTotals }) {
  const sum = TOKEN_TYPES.reduce((acc, t) => acc + totals[t.key], 0)

  return (
    <div className="flex flex-col gap-3 py-3.5">
      <div className="flex h-2.5 w-full overflow-hidden rounded-full bg-muted">
        {sum > 0 &&
          TOKEN_TYPES.map((t) =>
            totals[t.key] > 0 ? (
              <Tooltip key={t.key}>
                <TooltipTrigger
                  render={
                    <div
                      className={cn("h-full", t.color)}
                      style={{ width: `${(totals[t.key] / sum) * 100}%` }}
                    />
                  }
                />
                <TooltipContent>
                  {t.label}: {fullFormat.format(totals[t.key])} tokens (
                  {((totals[t.key] / sum) * 100).toFixed(1)}%)
                </TooltipContent>
              </Tooltip>
            ) : null
          )}
      </div>
      <div className="grid grid-cols-2 gap-x-6 gap-y-2 sm:grid-cols-4">
        {TOKEN_TYPES.map((t) => (
          <div key={t.key} className="flex flex-col gap-0.5">
            <div className="flex items-center gap-1.5">
              <span className={cn("size-2 rounded-full", t.color)} />
              <span className="text-xs text-muted-foreground">{t.label}</span>
            </div>
            <span className="text-sm font-medium tabular-nums">
              {formatTokens(totals[t.key])}
            </span>
            <span className="text-[11px] text-muted-foreground">
              {t.description}
            </span>
          </div>
        ))}
      </div>
    </div>
  )
}

// ── Daily tokens chart ────────────────────────────────────────────────────────

const tokensChartConfig = {
  inputTokens: { label: "Input", color: "var(--chart-1)" },
  outputTokens: { label: "Output", color: "var(--chart-2)" },
  cacheReadTokens: { label: "Cache read", color: "var(--chart-3)" },
  cacheWriteTokens: { label: "Cache write", color: "var(--chart-4)" },
} satisfies ChartConfig

function DailyTokensChart({ daily }: { daily: AiUsageDaily[] }) {
  if (daily.length === 0) return <ChartEmpty />

  return (
    <div className="py-3.5">
      <ChartContainer
        config={tokensChartConfig}
        className="aspect-auto h-52 w-full"
      >
        <BarChart data={daily} margin={{ left: 0, right: 0, top: 4 }}>
          <CartesianGrid vertical={false} />
          <XAxis
            dataKey="day"
            tickLine={false}
            axisLine={false}
            tickMargin={6}
            minTickGap={28}
            tickFormatter={formatDayShort}
          />
          <YAxis
            tickLine={false}
            axisLine={false}
            width={44}
            tickFormatter={(value: number) => compactFormat.format(value)}
          />
          <ChartTooltip
            content={
              <ChartTooltipContent
                labelFormatter={(_, payload) =>
                  formatDayFull(String(payload?.[0]?.payload?.day ?? ""))
                }
              />
            }
          />
          <ChartLegend content={<ChartLegendContent />} />
          <Bar
            dataKey="inputTokens"
            stackId="tokens"
            fill="var(--color-inputTokens)"
          />
          <Bar
            dataKey="outputTokens"
            stackId="tokens"
            fill="var(--color-outputTokens)"
          />
          <Bar
            dataKey="cacheReadTokens"
            stackId="tokens"
            fill="var(--color-cacheReadTokens)"
          />
          <Bar
            dataKey="cacheWriteTokens"
            stackId="tokens"
            fill="var(--color-cacheWriteTokens)"
          />
        </BarChart>
      </ChartContainer>
    </div>
  )
}

// ── Daily cost chart ──────────────────────────────────────────────────────────

const costChartConfig = {
  cost: { label: "Daily cost", color: "var(--chart-2)" },
  cumulativeCost: { label: "Running total", color: "var(--chart-5)" },
} satisfies ChartConfig

function DailyCostChart({ daily }: { daily: AiUsageDaily[] }) {
  const data = useMemo(() => {
    const result: { day: string; cost: number; cumulativeCost: number }[] = []
    for (const d of daily) {
      const previous =
        result.length > 0 ? result[result.length - 1].cumulativeCost : 0
      result.push({
        day: d.day,
        cost: d.cost,
        cumulativeCost: previous + d.cost,
      })
    }
    return result
  }, [daily])

  if (data.length === 0) return <ChartEmpty />

  return (
    <div className="py-3.5">
      <ChartContainer
        config={costChartConfig}
        className="aspect-auto h-52 w-full"
      >
        <ComposedChart data={data} margin={{ left: 0, right: 0, top: 4 }}>
          <CartesianGrid vertical={false} />
          <XAxis
            dataKey="day"
            tickLine={false}
            axisLine={false}
            tickMargin={6}
            minTickGap={28}
            tickFormatter={formatDayShort}
          />
          <YAxis
            yAxisId="daily"
            tickLine={false}
            axisLine={false}
            width={48}
            tickFormatter={(value: number) => formatCost(value)}
          />
          <YAxis
            yAxisId="cumulative"
            orientation="right"
            tickLine={false}
            axisLine={false}
            width={48}
            tickFormatter={(value: number) => formatCost(value)}
          />
          <ChartTooltip
            content={
              <ChartTooltipContent
                labelFormatter={(_, payload) =>
                  formatDayFull(String(payload?.[0]?.payload?.day ?? ""))
                }
                formatter={(value, name) => (
                  <div className="flex w-full items-center justify-between gap-4">
                    <span className="text-muted-foreground">
                      {costChartConfig[name as keyof typeof costChartConfig]
                        ?.label ?? name}
                    </span>
                    <span className="font-mono font-medium tabular-nums">
                      {formatCost(Number(value))}
                    </span>
                  </div>
                )}
              />
            }
          />
          <ChartLegend content={<ChartLegendContent />} />
          <Bar yAxisId="daily" dataKey="cost" fill="var(--color-cost)" />
          <Line
            yAxisId="cumulative"
            type="monotone"
            dataKey="cumulativeCost"
            stroke="var(--color-cumulativeCost)"
            strokeWidth={1.5}
            dot={false}
          />
        </ComposedChart>
      </ChartContainer>
    </div>
  )
}

function ChartEmpty() {
  return (
    <p className="py-8 text-center text-xs text-muted-foreground">
      Nothing recorded in this period.
    </p>
  )
}

// ── Cost by model chart ───────────────────────────────────────────────────────

const MODEL_SLICE_COLORS = [
  "var(--chart-1)",
  "var(--chart-2)",
  "var(--chart-3)",
  "var(--chart-4)",
  "var(--chart-5)",
]

function ModelCostChart({
  models,
  totals,
}: {
  models: AiUsageByModel[]
  totals: AiUsageTotals
}) {
  const { data, config } = useMemo(() => {
    const withCost = models.filter((m) => m.cost > 0)
    const top = withCost.slice(0, MODEL_SLICE_COLORS.length - 1)
    const rest = withCost.slice(MODEL_SLICE_COLORS.length - 1)
    const slices = top.map((m, i) => ({
      key: `model${i}`,
      name: m.model || "Unknown model",
      cost: m.cost,
      fill: MODEL_SLICE_COLORS[i],
    }))
    if (rest.length > 0) {
      slices.push({
        key: "modelOther",
        name: `Other (${rest.length})`,
        cost: rest.reduce((acc, m) => acc + m.cost, 0),
        fill: MODEL_SLICE_COLORS[MODEL_SLICE_COLORS.length - 1],
      })
    }
    const config = Object.fromEntries(
      slices.map((s) => [s.key, { label: s.name, color: s.fill }])
    ) satisfies ChartConfig
    return { data: slices, config }
  }, [models])

  if (data.length === 0) return null

  return (
    <div className="py-3.5">
      <ChartContainer config={config} className="mx-auto aspect-auto h-56">
        <PieChart>
          <ChartTooltip
            content={
              <ChartTooltipContent
                nameKey="key"
                hideLabel
                formatter={(value, _name, item) => (
                  <div className="flex w-full items-center justify-between gap-4">
                    <span className="text-muted-foreground">
                      {item?.payload?.name}
                    </span>
                    <span className="font-mono font-medium tabular-nums">
                      {formatCost(Number(value))}
                    </span>
                  </div>
                )}
              />
            }
          />
          <Pie
            data={data}
            dataKey="cost"
            nameKey="key"
            innerRadius={55}
            strokeWidth={4}
          >
            <Label
              content={({ viewBox }) => {
                if (!viewBox || !("cx" in viewBox) || !("cy" in viewBox)) {
                  return null
                }
                return (
                  <text
                    x={viewBox.cx}
                    y={viewBox.cy}
                    textAnchor="middle"
                    dominantBaseline="middle"
                  >
                    <tspan
                      x={viewBox.cx}
                      y={viewBox.cy}
                      className="fill-foreground text-base font-semibold tabular-nums"
                    >
                      {formatCost(totals.cost)}
                    </tspan>
                    <tspan
                      x={viewBox.cx}
                      y={(viewBox.cy ?? 0) + 16}
                      className="fill-muted-foreground text-[10px]"
                    >
                      total cost
                    </tspan>
                  </text>
                )
              }}
            />
          </Pie>
          <ChartLegend
            content={<ChartLegendContent nameKey="key" />}
            className="flex-wrap gap-x-4 gap-y-1 *:justify-center"
          />
        </PieChart>
      </ChartContainer>
    </div>
  )
}

// ── Model table ───────────────────────────────────────────────────────────────

function ModelTable({ models }: { models: AiUsageByModel[] }) {
  return (
    <div className="overflow-x-auto py-3.5">
      <table className="w-full text-xs">
        <thead>
          <tr className="border-b border-border/50 text-left text-muted-foreground">
            <th className="pr-3 pb-2 font-medium">Model</th>
            <th className="pr-3 pb-2 text-right font-medium">Requests</th>
            <th className="pr-3 pb-2 text-right font-medium">Input</th>
            <th className="pr-3 pb-2 text-right font-medium">Output</th>
            <th className="pr-3 pb-2 text-right font-medium">Cache read</th>
            <th className="pr-3 pb-2 text-right font-medium">Cache write</th>
            <th className="pr-3 pb-2 text-right font-medium">Total</th>
            <th className="pb-2 text-right font-medium">Cost</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-border/30">
          {models.map((m) => (
            <tr key={`${m.provider}/${m.model}`}>
              <td className="max-w-48 py-2 pr-3">
                <div className="flex items-center gap-1.5">
                  <span className="truncate font-medium">
                    {m.model || "Unknown model"}
                  </span>
                  {m.provider && (
                    <Badge variant="secondary" className="shrink-0 text-[10px]">
                      {m.provider}
                    </Badge>
                  )}
                </div>
              </td>
              <td className="py-2 pr-3 text-right tabular-nums">
                {fullFormat.format(m.requests)}
              </td>
              <td className="py-2 pr-3 text-right tabular-nums">
                {formatTokens(m.inputTokens)}
              </td>
              <td className="py-2 pr-3 text-right tabular-nums">
                {formatTokens(m.outputTokens)}
              </td>
              <td className="py-2 pr-3 text-right tabular-nums">
                {formatTokens(m.cacheReadTokens)}
              </td>
              <td className="py-2 pr-3 text-right tabular-nums">
                {formatTokens(m.cacheWriteTokens)}
              </td>
              <td className="py-2 pr-3 text-right font-medium tabular-nums">
                {formatTokens(m.totalTokens)}
              </td>
              <td className="py-2 text-right tabular-nums">
                {formatCost(m.cost)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

// ── Workspace cards ───────────────────────────────────────────────────────────

function WorkspaceCard({ workspace }: { workspace: AiUsageByWorkspace }) {
  return (
    <div className="rounded-lg border border-border/60">
      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-border/40 px-3 py-2.5">
        <div className="flex min-w-0 items-center gap-2">
          <FolderGit2 className="size-4 shrink-0 text-muted-foreground" />
          <span className="truncate text-sm font-medium">
            {workspace.workspaceName ?? "Deleted workspace"}
          </span>
          <span className="shrink-0 text-[11px] text-muted-foreground">
            {workspace.threads} {workspace.threads === 1 ? "thread" : "threads"}{" "}
            · {fullFormat.format(workspace.requests)} requests
          </span>
        </div>
        <div className="flex shrink-0 items-center gap-3 text-xs tabular-nums">
          <span className="font-medium">
            {formatTokens(workspace.totalTokens)} tokens
          </span>
          <span className="text-muted-foreground">
            {formatCost(workspace.cost)}
          </span>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-x-6 gap-y-1 px-3 py-2 sm:grid-cols-4">
        <WorkspaceStat
          icon={ArrowUpFromLine}
          label="Input"
          value={formatTokens(workspace.inputTokens)}
        />
        <WorkspaceStat
          icon={ArrowDownToLine}
          label="Output"
          value={formatTokens(workspace.outputTokens)}
        />
        <WorkspaceStat
          icon={DatabaseZap}
          label="Cache read"
          value={formatTokens(workspace.cacheReadTokens)}
        />
        <WorkspaceStat
          icon={DatabaseZap}
          label="Cache write"
          value={formatTokens(workspace.cacheWriteTokens)}
        />
      </div>

      {workspace.models.length > 0 && (
        <div className="border-t border-border/40 px-3 py-2">
          <div className="flex flex-col gap-1.5">
            {workspace.models.map((m) => (
              <div
                key={`${m.provider}/${m.model}`}
                className="flex items-center justify-between gap-3 text-xs"
              >
                <div className="flex min-w-0 items-center gap-1.5">
                  <span className="truncate">{m.model || "Unknown model"}</span>
                  {m.provider && (
                    <Badge variant="secondary" className="shrink-0 text-[10px]">
                      {m.provider}
                    </Badge>
                  )}
                </div>
                <div className="flex shrink-0 items-center gap-3 text-muted-foreground tabular-nums">
                  <span>{fullFormat.format(m.requests)} req</span>
                  <span>{formatTokens(m.totalTokens)} tokens</span>
                  <span>{formatCost(m.cost)}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

function WorkspaceStat({
  icon: Icon,
  label,
  value,
}: {
  icon: React.ComponentType<{ className?: string }>
  label: string
  value: string
}) {
  return (
    <div className="flex items-center gap-1.5 text-xs">
      <Icon className="size-3 text-muted-foreground" />
      <span className="text-muted-foreground">{label}</span>
      <span className="ml-auto font-medium tabular-nums">{value}</span>
    </div>
  )
}
