import { useMemo, useState } from "react"
import {
  ArrowDownToLine,
  ArrowUpFromLine,
  ChartColumn,
  CircleDollarSign,
  DatabaseZap,
  FolderGit2,
  MessagesSquare,
} from "lucide-react"

import { Badge } from "@/shared/ui/badge"
import { Skeleton } from "@/shared/ui/skeleton"
import { Tabs, TabsList, TabsTrigger } from "@/shared/ui/tabs"
import { Tooltip, TooltipContent, TooltipTrigger } from "@/shared/ui/tooltip"
import { cn } from "@/shared/lib/utils"

import type {
  AiUsageByModel,
  AiUsageByWorkspace,
  AiUsageDaily,
  AiUsageTotals,
} from "../api"
import { useAiUsage } from "../queries"
import { SettingsGroup } from "../components/settings-ui"

// ── Formatting ────────────────────────────────────────────────────────────────

const compactFormat = new Intl.NumberFormat("en-US", {
  notation: "compact",
  maximumFractionDigits: 1,
})
const fullFormat = new Intl.NumberFormat("en-US")

function formatTokens(n: number): string {
  return n >= 10_000 ? compactFormat.format(n) : fullFormat.format(n)
}

function formatCost(n: number): string {
  if (n === 0) return "$0.00"
  if (n < 0.01) return `$${n.toFixed(4)}`
  return `$${n.toFixed(2)}`
}

function formatDay(day: string): string {
  const date = new Date(`${day}T00:00:00`)
  return date.toLocaleDateString(undefined, { month: "short", day: "numeric" })
}

// ── Token-type metadata ───────────────────────────────────────────────────────

const TOKEN_TYPES = [
  {
    key: "inputTokens",
    label: "Input",
    color: "bg-chart-1",
    description: "Uncached prompt tokens sent to the model",
  },
  {
    key: "outputTokens",
    label: "Output",
    color: "bg-chart-2",
    description: "Tokens generated by the model",
  },
  {
    key: "cacheReadTokens",
    label: "Cache read",
    color: "bg-chart-3",
    description: "Prompt tokens served from the provider's cache",
  },
  {
    key: "cacheWriteTokens",
    label: "Cache write",
    color: "bg-chart-4",
    description: "Prompt tokens written to the provider's cache",
  },
] as const satisfies readonly {
  key: keyof AiUsageTotals
  label: string
  color: string
  description: string
}[]

const RANGES = [
  { days: 7, label: "7 days" },
  { days: 30, label: "30 days" },
  { days: 0, label: "All time" },
] as const

// ── Section ───────────────────────────────────────────────────────────────────

export function UsageSection() {
  const [days, setDays] = useState<number>(30)
  const { data, isPending, isError } = useAiUsage(days)

  return (
    <>
      <Tabs
        value={String(days)}
        onValueChange={(value) => setDays(Number(value))}
      >
        <TabsList>
          {RANGES.map((range) => (
            <TabsTrigger key={range.days} value={String(range.days)}>
              {range.label}
            </TabsTrigger>
          ))}
        </TabsList>
      </Tabs>

      {isPending ? (
        <UsageSkeleton />
      ) : isError ? (
        <p className="py-8 text-center text-sm text-muted-foreground">
          Failed to load usage data. Is the server running?
        </p>
      ) : data.totals.requests === 0 ? (
        <EmptyState />
      ) : (
        <>
          <OverviewCards totals={data.totals} />
          <SettingsGroup
            title="Token types"
            description="How the consumed tokens break down by kind."
          >
            <TokenTypeBreakdown totals={data.totals} />
          </SettingsGroup>
          <SettingsGroup
            title="Daily activity"
            description="Total tokens consumed per day."
          >
            <DailyChart daily={data.daily} days={days} />
          </SettingsGroup>
          <SettingsGroup
            title="Models"
            description="Every model used in the selected period."
          >
            <ModelTable models={data.byModel} />
          </SettingsGroup>
          <SettingsGroup
            title="Workspaces"
            description="Usage per workspace, with the models used in each."
          >
            <div className="flex flex-col gap-4 py-3.5">
              {data.byWorkspace.map((ws) => (
                <WorkspaceCard key={ws.workspaceId} workspace={ws} />
              ))}
            </div>
          </SettingsGroup>
        </>
      )}
    </>
  )
}

function EmptyState() {
  return (
    <div className="flex flex-col items-center gap-2 py-16 text-center">
      <ChartColumn className="size-8 text-muted-foreground/50" />
      <p className="text-sm font-medium">No usage recorded yet</p>
      <p className="max-w-sm text-xs text-muted-foreground">
        Token usage is recorded every time the agent responds. Start a
        conversation in any workspace and the dashboard will fill in.
      </p>
    </div>
  )
}

function UsageSkeleton() {
  return (
    <div className="flex flex-col gap-4">
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
        {Array.from({ length: 4 }).map((_, i) => (
          <Skeleton key={i} className="h-20 rounded-lg" />
        ))}
      </div>
      <Skeleton className="h-32 rounded-lg" />
      <Skeleton className="h-48 rounded-lg" />
    </div>
  )
}

// ── Overview cards ────────────────────────────────────────────────────────────

function OverviewCards({ totals }: { totals: AiUsageTotals }) {
  const cards = [
    {
      label: "Total tokens",
      value: formatTokens(totals.totalTokens),
      detail: `${fullFormat.format(totals.totalTokens)} tokens`,
      icon: ChartColumn,
    },
    {
      label: "Estimated cost",
      value: formatCost(totals.cost),
      detail: "Based on provider list prices",
      icon: CircleDollarSign,
    },
    {
      label: "Requests",
      value: fullFormat.format(totals.requests),
      detail: "LLM responses received",
      icon: MessagesSquare,
    },
    {
      label: "Output tokens",
      value: formatTokens(totals.outputTokens),
      detail: `${fullFormat.format(totals.outputTokens)} generated`,
      icon: ArrowDownToLine,
    },
  ]

  return (
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
      {cards.map((card) => (
        <div
          key={card.label}
          className="flex flex-col gap-1 rounded-lg border border-border/60 p-3"
        >
          <div className="flex items-center gap-1.5 text-muted-foreground">
            <card.icon className="size-3.5" />
            <span className="text-xs">{card.label}</span>
          </div>
          <span className="text-xl font-semibold tracking-tight tabular-nums">
            {card.value}
          </span>
          <span className="truncate text-[11px] text-muted-foreground">
            {card.detail}
          </span>
        </div>
      ))}
    </div>
  )
}

// ── Token type breakdown ──────────────────────────────────────────────────────

function TokenTypeBreakdown({ totals }: { totals: AiUsageTotals }) {
  const sum = TOKEN_TYPES.reduce((acc, t) => acc + totals[t.key], 0)

  return (
    <div className="flex flex-col gap-3 py-3.5">
      <div className="flex h-2.5 w-full overflow-hidden rounded-full bg-muted">
        {sum > 0 &&
          TOKEN_TYPES.map((t) =>
            totals[t.key] > 0 ? (
              <Tooltip key={t.key}>
                <TooltipTrigger
                  render={
                    <div
                      className={cn("h-full", t.color)}
                      style={{ width: `${(totals[t.key] / sum) * 100}%` }}
                    />
                  }
                />
                <TooltipContent>
                  {t.label}: {fullFormat.format(totals[t.key])} tokens (
                  {((totals[t.key] / sum) * 100).toFixed(1)}%)
                </TooltipContent>
              </Tooltip>
            ) : null,
          )}
      </div>
      <div className="grid grid-cols-2 gap-x-6 gap-y-2 sm:grid-cols-4">
        {TOKEN_TYPES.map((t) => (
          <div key={t.key} className="flex flex-col gap-0.5">
            <div className="flex items-center gap-1.5">
              <span className={cn("size-2 rounded-full", t.color)} />
              <span className="text-xs text-muted-foreground">{t.label}</span>
            </div>
            <span className="text-sm font-medium tabular-nums">
              {formatTokens(totals[t.key])}
            </span>
            <span className="text-[11px] text-muted-foreground">
              {t.description}
            </span>
          </div>
        ))}
      </div>
    </div>
  )
}

// ── Daily chart ───────────────────────────────────────────────────────────────

function DailyChart({ daily, days }: { daily: AiUsageDaily[]; days: number }) {
  const bars = useMemo(() => {
    const byDay = new Map(daily.map((d) => [d.day, d]))
    // Fixed ranges show every calendar day (including gaps); all-time shows
    // only recorded days, capped to the most recent 60.
    if (days === 0) return daily.slice(-60)
    const result: AiUsageDaily[] = []
    for (let i = days - 1; i >= 0; i--) {
      const date = new Date()
      date.setDate(date.getDate() - i)
      const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`
      result.push(
        byDay.get(key) ?? {
          day: key,
          inputTokens: 0,
          outputTokens: 0,
          cacheReadTokens: 0,
          cacheWriteTokens: 0,
          totalTokens: 0,
          cost: 0,
        },
      )
    }
    return result
  }, [daily, days])

  const max = Math.max(...bars.map((b) => b.totalTokens), 1)

  return (
    <div className="py-3.5">
      <div className="flex h-28 items-end gap-px">
        {bars.map((bar) => (
          <Tooltip key={bar.day}>
            <TooltipTrigger
              render={
                <div className="group flex h-full flex-1 items-end px-px">
                  <div
                    className={cn(
                      "w-full rounded-t-sm transition-colors",
                      bar.totalTokens > 0
                        ? "bg-chart-1 group-hover:bg-chart-1/80"
                        : "bg-muted",
                    )}
                    style={{
                      height:
                        bar.totalTokens > 0
                          ? `${Math.max((bar.totalTokens / max) * 100, 2)}%`
                          : "2px",
                    }}
                  />
                </div>
              }
            />
            <TooltipContent>
              <div className="flex flex-col gap-0.5">
                <span className="font-medium">{formatDay(bar.day)}</span>
                <span>{fullFormat.format(bar.totalTokens)} tokens</span>
                <span>{formatCost(bar.cost)}</span>
              </div>
            </TooltipContent>
          </Tooltip>
        ))}
      </div>
      <div className="mt-1.5 flex justify-between text-[10px] text-muted-foreground">
        <span>{bars.length > 0 ? formatDay(bars[0].day) : ""}</span>
        <span>
          {bars.length > 1 ? formatDay(bars[bars.length - 1].day) : ""}
        </span>
      </div>
    </div>
  )
}

// ── Model table ───────────────────────────────────────────────────────────────

function ModelTable({ models }: { models: AiUsageByModel[] }) {
  return (
    <div className="overflow-x-auto py-3.5">
      <table className="w-full text-xs">
        <thead>
          <tr className="border-b border-border/50 text-left text-muted-foreground">
            <th className="pb-2 pr-3 font-medium">Model</th>
            <th className="pb-2 pr-3 text-right font-medium">Requests</th>
            <th className="pb-2 pr-3 text-right font-medium">Input</th>
            <th className="pb-2 pr-3 text-right font-medium">Output</th>
            <th className="pb-2 pr-3 text-right font-medium">Cache read</th>
            <th className="pb-2 pr-3 text-right font-medium">Cache write</th>
            <th className="pb-2 pr-3 text-right font-medium">Total</th>
            <th className="pb-2 text-right font-medium">Cost</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-border/30">
          {models.map((m) => (
            <tr key={`${m.provider}/${m.model}`}>
              <td className="max-w-48 py-2 pr-3">
                <div className="flex items-center gap-1.5">
                  <span className="truncate font-medium">
                    {m.model || "Unknown model"}
                  </span>
                  {m.provider && (
                    <Badge variant="secondary" className="shrink-0 text-[10px]">
                      {m.provider}
                    </Badge>
                  )}
                </div>
              </td>
              <td className="py-2 pr-3 text-right tabular-nums">
                {fullFormat.format(m.requests)}
              </td>
              <td className="py-2 pr-3 text-right tabular-nums">
                {formatTokens(m.inputTokens)}
              </td>
              <td className="py-2 pr-3 text-right tabular-nums">
                {formatTokens(m.outputTokens)}
              </td>
              <td className="py-2 pr-3 text-right tabular-nums">
                {formatTokens(m.cacheReadTokens)}
              </td>
              <td className="py-2 pr-3 text-right tabular-nums">
                {formatTokens(m.cacheWriteTokens)}
              </td>
              <td className="py-2 pr-3 text-right font-medium tabular-nums">
                {formatTokens(m.totalTokens)}
              </td>
              <td className="py-2 text-right tabular-nums">
                {formatCost(m.cost)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

// ── Workspace cards ───────────────────────────────────────────────────────────

function WorkspaceCard({ workspace }: { workspace: AiUsageByWorkspace }) {
  return (
    <div className="rounded-lg border border-border/60">
      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-border/40 px-3 py-2.5">
        <div className="flex min-w-0 items-center gap-2">
          <FolderGit2 className="size-4 shrink-0 text-muted-foreground" />
          <span className="truncate text-sm font-medium">
            {workspace.workspaceName ?? "Deleted workspace"}
          </span>
          <span className="shrink-0 text-[11px] text-muted-foreground">
            {workspace.threads} {workspace.threads === 1 ? "thread" : "threads"}{" "}
            · {fullFormat.format(workspace.requests)} requests
          </span>
        </div>
        <div className="flex shrink-0 items-center gap-3 text-xs tabular-nums">
          <span className="font-medium">
            {formatTokens(workspace.totalTokens)} tokens
          </span>
          <span className="text-muted-foreground">
            {formatCost(workspace.cost)}
          </span>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-x-6 gap-y-1 px-3 py-2 sm:grid-cols-4">
        <WorkspaceStat
          icon={ArrowUpFromLine}
          label="Input"
          value={formatTokens(workspace.inputTokens)}
        />
        <WorkspaceStat
          icon={ArrowDownToLine}
          label="Output"
          value={formatTokens(workspace.outputTokens)}
        />
        <WorkspaceStat
          icon={DatabaseZap}
          label="Cache read"
          value={formatTokens(workspace.cacheReadTokens)}
        />
        <WorkspaceStat
          icon={DatabaseZap}
          label="Cache write"
          value={formatTokens(workspace.cacheWriteTokens)}
        />
      </div>

      {workspace.models.length > 0 && (
        <div className="border-t border-border/40 px-3 py-2">
          <div className="flex flex-col gap-1.5">
            {workspace.models.map((m) => (
              <div
                key={`${m.provider}/${m.model}`}
                className="flex items-center justify-between gap-3 text-xs"
              >
                <div className="flex min-w-0 items-center gap-1.5">
                  <span className="truncate">{m.model || "Unknown model"}</span>
                  {m.provider && (
                    <Badge variant="secondary" className="shrink-0 text-[10px]">
                      {m.provider}
                    </Badge>
                  )}
                </div>
                <div className="flex shrink-0 items-center gap-3 tabular-nums text-muted-foreground">
                  <span>{fullFormat.format(m.requests)} req</span>
                  <span>{formatTokens(m.totalTokens)} tokens</span>
                  <span>{formatCost(m.cost)}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

function WorkspaceStat({
  icon: Icon,
  label,
  value,
}: {
  icon: React.ComponentType<{ className?: string }>
  label: string
  value: string
}) {
  return (
    <div className="flex items-center gap-1.5 text-xs">
      <Icon className="size-3 text-muted-foreground" />
      <span className="text-muted-foreground">{label}</span>
      <span className="ml-auto font-medium tabular-nums">{value}</span>
    </div>
  )
}
