/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as NewRouteImport } from './routes/new'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as WorkspaceThreadIdRouteImport } from './routes/workspace.$threadId'
import { Route as SkillsIdRouteImport } from './routes/skills.$id'
import { Route as SettingsSectionRouteImport } from './routes/settings.$section'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const WorkspaceThreadIdRoute = WorkspaceThreadIdRouteImport.update({
  id: '/workspace/$threadId',
  path: '/workspace/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIdRoute = SkillsIdRouteImport.update({
  id: '/skills/$id',
  path: '/skills/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSectionRoute = SettingsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/new': typeof NewRoute
  '/onboard': typeof OnboardRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/$section': typeof SettingsSectionRoute
  '/skills/$id': typeof SkillsIdRoute
  '/workspace/$threadId': typeof WorkspaceThreadIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/skills/': typeof SkillsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/new': typeof NewRoute
  '/onboard': typeof OnboardRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/skills/$id': typeof SkillsIdRoute
  '/workspace/$threadId': typeof WorkspaceThreadIdRoute
  '/settings': typeof SettingsIndexRoute
  '/skills': typeof SkillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/new': typeof NewRoute
  '/onboard': typeof OnboardRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/$section': typeof SettingsSectionRoute
  '/skills/$id': typeof SkillsIdRoute
  '/workspace/$threadId': typeof WorkspaceThreadIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/skills/': typeof SkillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automations'
    | '/new'
    | '/onboard'
    | '/settings'
    | '/settings/$section'
    | '/skills/$id'
    | '/workspace/$threadId'
    | '/settings/'
    | '/skills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automations'
    | '/new'
    | '/onboard'
    | '/settings/$section'
    | '/skills/$id'
    | '/workspace/$threadId'
    | '/settings'
    | '/skills'
  id:
    | '__root__'
    | '/'
    | '/automations'
    | '/new'
    | '/onboard'
    | '/settings'
    | '/settings/$section'
    | '/skills/$id'
    | '/workspace/$threadId'
    | '/settings/'
    | '/skills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationsRoute: typeof AutomationsRoute
  NewRoute: typeof NewRoute
  OnboardRoute: typeof OnboardRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SkillsIdRoute: typeof SkillsIdRoute
  WorkspaceThreadIdRoute: typeof WorkspaceThreadIdRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/workspace/$threadId': {
      id: '/workspace/$threadId'
      path: '/workspace/$threadId'
      fullPath: '/workspace/$threadId'
      preLoaderRoute: typeof WorkspaceThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$id': {
      id: '/skills/$id'
      path: '/skills/$id'
      fullPath: '/skills/$id'
      preLoaderRoute: typeof SkillsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$section': {
      id: '/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof SettingsSectionRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsSectionRoute: typeof SettingsSectionRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSectionRoute: SettingsSectionRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationsRoute: AutomationsRoute,
  NewRoute: NewRoute,
  OnboardRoute: OnboardRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SkillsIdRoute: SkillsIdRoute,
  WorkspaceThreadIdRoute: WorkspaceThreadIdRoute,
  SkillsIndexRoute: SkillsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
