/**
 * Built-in color themes.
 *
 * Each theme provides a full {@link ThemePalette} for light and dark. The first
 * entry is the default and matches the palette baked into `index.css`
 * ("Jellybeans"), so users who never pick a theme see no change. `TypeScript`
 * enforces that every {@link ThemeColorKey} is present in each palette, so a
 * missing token is a compile error rather than a silent visual gap.
 */

import {
  jellybeansdark,
  jellybeanslight,
  jellybeanshljsdark,
  jellybeanshljslight,
} from "@/shared/lib/syntax-theme"
import type { ColorTheme, ThemePalette } from "./types"

// ── Jellybeans (default — mirrors index.css) ───────────────────────────────────

const jellybeansLight: ThemePalette = {
  background: "#f7f7f5",
  foreground: "#1c1c1c",
  card: "#f0f0ed",
  "card-foreground": "#1c1c1c",
  popover: "#f0f0ed",
  "popover-foreground": "#1c1c1c",
  primary: "#1a4080",
  "primary-foreground": "#f7f7f5",
  secondary: "#e8e8e4",
  "secondary-foreground": "#1c1c1c",
  muted: "#dcdcd8",
  "muted-foreground": "#6b6b6b",
  accent: "#d0d0cb",
  "accent-foreground": "#1c1c1c",
  destructive: "#902020",
  border: "#e3e3df",
  input: "#d9d9d4",
  ring: "#1a4080",
  "chart-1": "#1a4080",
  "chart-2": "#5a7842",
  "chart-3": "#c4870a",
  "chart-4": "#9f4e32",
  "chart-5": "#a06820",
  sidebar: "#ededea",
  "sidebar-foreground": "#1c1c1c",
  "sidebar-primary": "#1a4080",
  "sidebar-primary-foreground": "#f7f7f5",
  "sidebar-accent": "#e5e5e1",
  "sidebar-accent-foreground": "#1c1c1c",
  "sidebar-border": "#dcdcd8",
  "sidebar-ring": "#1a4080",
}

const jellybeansDark: ThemePalette = {
  background: "#0d0d0d",
  foreground: "#e8e8d3",
  card: "#161616",
  "card-foreground": "#e8e8d3",
  popover: "#161616",
  "popover-foreground": "#e8e8d3",
  primary: "#3a6090",
  "primary-foreground": "#e8e8d3",
  secondary: "#222222",
  "secondary-foreground": "#e8e8d3",
  muted: "#2b2b2b",
  "muted-foreground": "#9e9e9e",
  accent: "#393939",
  "accent-foreground": "#e8e8d3",
  destructive: "#cc3333",
  border: "#1e1e1e",
  input: "#252525",
  ring: "#3a6090",
  "chart-1": "#3a6090",
  "chart-2": "#99ad6a",
  "chart-3": "#fad07a",
  "chart-4": "#cf6a4c",
  "chart-5": "#ffb964",
  sidebar: "#0a0a0a",
  "sidebar-foreground": "#e8e8d3",
  "sidebar-primary": "#3a6090",
  "sidebar-primary-foreground": "#e8e8d3",
  "sidebar-accent": "#1a1a1a",
  "sidebar-accent-foreground": "#e8e8d3",
  "sidebar-border": "#141414",
  "sidebar-ring": "#3a6090",
}

const jellybeans: ColorTheme = {
  id: "jellybeans",
  name: "Jellybeans",
  description: "The signature steel-blue palette. Warm, low-glare dark mode.",
  group: "Built-in",
  radius: "0.625rem",
  light: jellybeansLight,
  dark: jellybeansDark,
  // Hand-tuned code palettes (Fleet-derived) for maximum fidelity.
  syntax: {
    light: { prism: jellybeanslight, hljs: jellybeanshljslight },
    dark: { prism: jellybeansdark, hljs: jellybeanshljsdark },
  },
}

// ── Graphite (neutral, blue accent) ────────────────────────────────────────────

const graphite: ColorTheme = {
  id: "graphite",
  name: "Graphite",
  description: "Clean, neutral grays with a confident blue accent.",
  group: "Built-in",
  radius: "0.625rem",
  light: {
    background: "#fafafa",
    foreground: "#18181b",
    card: "#ffffff",
    "card-foreground": "#18181b",
    popover: "#ffffff",
    "popover-foreground": "#18181b",
    primary: "#2563eb",
    "primary-foreground": "#fafafa",
    secondary: "#f4f4f5",
    "secondary-foreground": "#18181b",
    muted: "#ededef",
    "muted-foreground": "#71717a",
    accent: "#e4e4e7",
    "accent-foreground": "#18181b",
    destructive: "#dc2626",
    border: "#e4e4e7",
    input: "#d4d4d8",
    ring: "#2563eb",
    "chart-1": "#2563eb",
    "chart-2": "#16a34a",
    "chart-3": "#d97706",
    "chart-4": "#db2777",
    "chart-5": "#7c3aed",
    sidebar: "#f4f4f5",
    "sidebar-foreground": "#18181b",
    "sidebar-primary": "#2563eb",
    "sidebar-primary-foreground": "#fafafa",
    "sidebar-accent": "#e4e4e7",
    "sidebar-accent-foreground": "#18181b",
    "sidebar-border": "#e4e4e7",
    "sidebar-ring": "#2563eb",
  },
  dark: {
    background: "#09090b",
    foreground: "#fafafa",
    card: "#18181b",
    "card-foreground": "#fafafa",
    popover: "#18181b",
    "popover-foreground": "#fafafa",
    primary: "#3b82f6",
    "primary-foreground": "#fafafa",
    secondary: "#27272a",
    "secondary-foreground": "#fafafa",
    muted: "#27272a",
    "muted-foreground": "#a1a1aa",
    accent: "#3f3f46",
    "accent-foreground": "#fafafa",
    destructive: "#ef4444",
    border: "#27272a",
    input: "#3f3f46",
    ring: "#3b82f6",
    "chart-1": "#3b82f6",
    "chart-2": "#4ade80",
    "chart-3": "#fbbf24",
    "chart-4": "#f472b6",
    "chart-5": "#a78bfa",
    sidebar: "#09090b",
    "sidebar-foreground": "#fafafa",
    "sidebar-primary": "#3b82f6",
    "sidebar-primary-foreground": "#fafafa",
    "sidebar-accent": "#18181b",
    "sidebar-accent-foreground": "#fafafa",
    "sidebar-border": "#1c1c1f",
    "sidebar-ring": "#3b82f6",
  },
}

// ── macOS (Apple HIG system colors) ─────────────────────────────────────────────

const macos: ColorTheme = {
  id: "macos",
  name: "macOS",
  description: "Apple system colors. Feels right at home on a Mac.",
  group: "Built-in",
  radius: "0.625rem",
  light: {
    background: "#f5f5f7",
    foreground: "#1d1d1f",
    card: "#ffffff",
    "card-foreground": "#1d1d1f",
    popover: "#ffffff",
    "popover-foreground": "#1d1d1f",
    primary: "#007aff",
    "primary-foreground": "#ffffff",
    secondary: "#eaeaef",
    "secondary-foreground": "#1d1d1f",
    muted: "#e3e3e8",
    "muted-foreground": "#6e6e73",
    accent: "#d9d9e0",
    "accent-foreground": "#1d1d1f",
    destructive: "#ff3b30",
    border: "#e0e0e5",
    input: "#d1d1d6",
    ring: "#007aff",
    "chart-1": "#007aff",
    "chart-2": "#34c759",
    "chart-3": "#ff9500",
    "chart-4": "#ff2d55",
    "chart-5": "#af52de",
    sidebar: "#ececf0",
    "sidebar-foreground": "#1d1d1f",
    "sidebar-primary": "#007aff",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#dfdfe4",
    "sidebar-accent-foreground": "#1d1d1f",
    "sidebar-border": "#dcdce1",
    "sidebar-ring": "#007aff",
  },
  dark: {
    background: "#161618",
    foreground: "#f5f5f7",
    card: "#202023",
    "card-foreground": "#f5f5f7",
    popover: "#242427",
    "popover-foreground": "#f5f5f7",
    primary: "#0a84ff",
    "primary-foreground": "#ffffff",
    secondary: "#2a2a2e",
    "secondary-foreground": "#f5f5f7",
    muted: "#323237",
    "muted-foreground": "#98989d",
    accent: "#38383e",
    "accent-foreground": "#f5f5f7",
    destructive: "#ff453a",
    border: "#28282c",
    input: "#36363c",
    ring: "#0a84ff",
    "chart-1": "#0a84ff",
    "chart-2": "#30d158",
    "chart-3": "#ff9f0a",
    "chart-4": "#ff375f",
    "chart-5": "#bf5af2",
    sidebar: "#111113",
    "sidebar-foreground": "#f5f5f7",
    "sidebar-primary": "#0a84ff",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#222226",
    "sidebar-accent-foreground": "#f5f5f7",
    "sidebar-border": "#1e1e22",
    "sidebar-ring": "#0a84ff",
  },
}

// ── Nord (arctic, frost accent) ─────────────────────────────────────────────────

const nord: ColorTheme = {
  id: "nord",
  name: "Nord",
  description: "An arctic, north-bluish palette. Cool and calm.",
  group: "Built-in",
  radius: "0.625rem",
  light: {
    background: "#eceff4",
    foreground: "#2e3440",
    card: "#f5f7fa",
    "card-foreground": "#2e3440",
    popover: "#f5f7fa",
    "popover-foreground": "#2e3440",
    primary: "#5e81ac",
    "primary-foreground": "#eceff4",
    secondary: "#e5e9f0",
    "secondary-foreground": "#2e3440",
    muted: "#dde3ec",
    "muted-foreground": "#4c566a",
    accent: "#d8dee9",
    "accent-foreground": "#2e3440",
    destructive: "#bf616a",
    border: "#dde3ec",
    input: "#d0d8e4",
    ring: "#5e81ac",
    "chart-1": "#5e81ac",
    "chart-2": "#5e8c5a",
    "chart-3": "#b07d48",
    "chart-4": "#a65d68",
    "chart-5": "#9a6a92",
    sidebar: "#e5e9f0",
    "sidebar-foreground": "#2e3440",
    "sidebar-primary": "#5e81ac",
    "sidebar-primary-foreground": "#eceff4",
    "sidebar-accent": "#d8dee9",
    "sidebar-accent-foreground": "#2e3440",
    "sidebar-border": "#d8dee9",
    "sidebar-ring": "#5e81ac",
  },
  dark: {
    background: "#2e3440",
    foreground: "#eceff4",
    card: "#3b4252",
    "card-foreground": "#eceff4",
    popover: "#3b4252",
    "popover-foreground": "#eceff4",
    primary: "#88c0d0",
    "primary-foreground": "#2e3440",
    secondary: "#434c5e",
    "secondary-foreground": "#eceff4",
    muted: "#434c5e",
    "muted-foreground": "#9aa3b2",
    accent: "#4c566a",
    "accent-foreground": "#eceff4",
    destructive: "#bf616a",
    /* Sits between card (#3b4252) and secondary (#434c5e) so card edges stay
       legible — a border equal to the card surface disappears entirely. */
    border: "#414a5e",
    input: "#434c5e",
    ring: "#88c0d0",
    "chart-1": "#81a1c1",
    "chart-2": "#a3be8c",
    "chart-3": "#ebcb8b",
    "chart-4": "#d08770",
    "chart-5": "#b48ead",
    sidebar: "#2b303b",
    "sidebar-foreground": "#eceff4",
    "sidebar-primary": "#88c0d0",
    "sidebar-primary-foreground": "#2e3440",
    "sidebar-accent": "#3b4252",
    "sidebar-accent-foreground": "#eceff4",
    "sidebar-border": "#353c4a",
    "sidebar-ring": "#88c0d0",
  },
}

// ── Rosé Pine (soft, natural) ───────────────────────────────────────────────────

const rosePine: ColorTheme = {
  id: "rose-pine",
  name: "Rosé Pine",
  description: "All natural pine, faux fur and a bit of soho vibes.",
  group: "Built-in",
  radius: "0.625rem",
  light: {
    background: "#faf4ed",
    foreground: "#575279",
    card: "#fffaf3",
    "card-foreground": "#575279",
    popover: "#fffaf3",
    "popover-foreground": "#575279",
    primary: "#907aa9",
    "primary-foreground": "#faf4ed",
    secondary: "#f2e9e1",
    "secondary-foreground": "#575279",
    muted: "#f2e9e1",
    "muted-foreground": "#797593",
    accent: "#dfdad9",
    "accent-foreground": "#575279",
    destructive: "#b4637a",
    border: "#dfdad9",
    input: "#cecacd",
    ring: "#907aa9",
    "chart-1": "#907aa9",
    "chart-2": "#56949f",
    "chart-3": "#ea9d34",
    "chart-4": "#b4637a",
    "chart-5": "#286983",
    sidebar: "#fffaf3",
    "sidebar-foreground": "#575279",
    "sidebar-primary": "#907aa9",
    "sidebar-primary-foreground": "#faf4ed",
    "sidebar-accent": "#f2e9e1",
    "sidebar-accent-foreground": "#575279",
    "sidebar-border": "#dfdad9",
    "sidebar-ring": "#907aa9",
  },
  dark: {
    background: "#191724",
    foreground: "#e0def4",
    card: "#1f1d2e",
    "card-foreground": "#e0def4",
    popover: "#1f1d2e",
    "popover-foreground": "#e0def4",
    primary: "#c4a7e7",
    "primary-foreground": "#191724",
    secondary: "#26233a",
    "secondary-foreground": "#e0def4",
    muted: "#26233a",
    "muted-foreground": "#908caa",
    accent: "#403d52",
    "accent-foreground": "#e0def4",
    destructive: "#eb6f92",
    border: "#26233a",
    input: "#403d52",
    ring: "#c4a7e7",
    "chart-1": "#c4a7e7",
    "chart-2": "#9ccfd8",
    "chart-3": "#f6c177",
    "chart-4": "#eb6f92",
    "chart-5": "#31748f",
    sidebar: "#1f1d2e",
    "sidebar-foreground": "#e0def4",
    "sidebar-primary": "#c4a7e7",
    "sidebar-primary-foreground": "#191724",
    "sidebar-accent": "#26233a",
    "sidebar-accent-foreground": "#e0def4",
    "sidebar-border": "#21202e",
    "sidebar-ring": "#c4a7e7",
  },
}

// ── Solarized (Ethan Schoonover) ────────────────────────────────────────────────

const solarized: ColorTheme = {
  id: "solarized",
  name: "Solarized",
  description: "Precision colors for machines and people. A timeless classic.",
  group: "Built-in",
  radius: "0.5rem",
  light: {
    background: "#fdf6e3",
    foreground: "#586e75",
    card: "#f4eed9",
    "card-foreground": "#586e75",
    popover: "#f4eed9",
    "popover-foreground": "#586e75",
    primary: "#268bd2",
    "primary-foreground": "#fdf6e3",
    secondary: "#eee8d5",
    "secondary-foreground": "#586e75",
    muted: "#e6dfc6",
    "muted-foreground": "#657b83",
    accent: "#ddd6c1",
    "accent-foreground": "#586e75",
    destructive: "#dc322f",
    border: "#e6dfc6",
    input: "#ddd6c1",
    ring: "#268bd2",
    "chart-1": "#268bd2",
    "chart-2": "#859900",
    "chart-3": "#b58900",
    "chart-4": "#cb4b16",
    "chart-5": "#6c71c4",
    sidebar: "#eee8d5",
    "sidebar-foreground": "#586e75",
    "sidebar-primary": "#268bd2",
    "sidebar-primary-foreground": "#fdf6e3",
    "sidebar-accent": "#e6dfc6",
    "sidebar-accent-foreground": "#586e75",
    "sidebar-border": "#ddd6c1",
    "sidebar-ring": "#268bd2",
  },
  dark: {
    background: "#002b36",
    foreground: "#93a1a1",
    card: "#073642",
    "card-foreground": "#93a1a1",
    popover: "#073642",
    "popover-foreground": "#93a1a1",
    primary: "#268bd2",
    "primary-foreground": "#002b36",
    secondary: "#073642",
    "secondary-foreground": "#93a1a1",
    muted: "#073642",
    "muted-foreground": "#586e75",
    accent: "#0a4554",
    "accent-foreground": "#93a1a1",
    destructive: "#dc322f",
    border: "#0a4453",
    input: "#0e5163",
    ring: "#268bd2",
    "chart-1": "#268bd2",
    "chart-2": "#859900",
    "chart-3": "#b58900",
    "chart-4": "#cb4b16",
    "chart-5": "#6c71c4",
    sidebar: "#00252e",
    "sidebar-foreground": "#93a1a1",
    "sidebar-primary": "#268bd2",
    "sidebar-primary-foreground": "#002b36",
    "sidebar-accent": "#073642",
    "sidebar-accent-foreground": "#93a1a1",
    "sidebar-border": "#0a4453",
    "sidebar-ring": "#268bd2",
  },
}

// ── Catppuccin (Latte light / Mocha dark, mauve accent) ─────────────────────────

const catppuccin: ColorTheme = {
  id: "catppuccin",
  name: "Catppuccin",
  description: "Soothing pastels for the high-spirited. Latte by day, Mocha by night.",
  group: "Built-in",
  radius: "0.625rem",
  light: {
    background: "#eff1f5",
    foreground: "#4c4f69",
    card: "#e6e9ef",
    "card-foreground": "#4c4f69",
    popover: "#e6e9ef",
    "popover-foreground": "#4c4f69",
    primary: "#8839ef",
    "primary-foreground": "#ffffff",
    secondary: "#dce0e8",
    "secondary-foreground": "#4c4f69",
    muted: "#ccd0da",
    "muted-foreground": "#6c6f85",
    accent: "#bcc0cc",
    "accent-foreground": "#4c4f69",
    destructive: "#d20f39",
    border: "#dce0e8",
    input: "#ccd0da",
    ring: "#8839ef",
    "chart-1": "#8839ef",
    "chart-2": "#40a02b",
    "chart-3": "#df8e1d",
    "chart-4": "#d20f39",
    "chart-5": "#1e66f5",
    sidebar: "#e6e9ef",
    "sidebar-foreground": "#4c4f69",
    "sidebar-primary": "#8839ef",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#d9dde7",
    "sidebar-accent-foreground": "#4c4f69",
    "sidebar-border": "#d5dae4",
    "sidebar-ring": "#8839ef",
  },
  dark: {
    background: "#1e1e2e",
    foreground: "#cdd6f4",
    card: "#252536",
    "card-foreground": "#cdd6f4",
    popover: "#252536",
    "popover-foreground": "#cdd6f4",
    primary: "#cba6f7",
    "primary-foreground": "#1e1e2e",
    secondary: "#313244",
    "secondary-foreground": "#cdd6f4",
    muted: "#393a52",
    "muted-foreground": "#a6adc8",
    accent: "#45475a",
    "accent-foreground": "#cdd6f4",
    destructive: "#f38ba8",
    border: "#2e2e45",
    input: "#3a3a55",
    ring: "#cba6f7",
    "chart-1": "#cba6f7",
    "chart-2": "#a6e3a1",
    "chart-3": "#f9e2af",
    "chart-4": "#f38ba8",
    "chart-5": "#89b4fa",
    sidebar: "#181825",
    "sidebar-foreground": "#cdd6f4",
    "sidebar-primary": "#cba6f7",
    "sidebar-primary-foreground": "#1e1e2e",
    "sidebar-accent": "#28283c",
    "sidebar-accent-foreground": "#cdd6f4",
    "sidebar-border": "#222233",
    "sidebar-ring": "#cba6f7",
  },
}

// ── Cursor Anysphere ────────────────────────────────────────────────────────────

const cursorAnysphere: ColorTheme = {
  id: "cursor-anysphere",
  name: "Cursor Anysphere",
  description: "Cursor's signature dark palette. Charcoal surfaces, neutral gray text, and a confident blue accent.",
  group: "Built-in",
  radius: "0.625rem",
  light: {
    background: "#f7f7f8",
    foreground: "#1a1a1a",
    card: "#ffffff",
    "card-foreground": "#1a1a1a",
    popover: "#ffffff",
    "popover-foreground": "#1a1a1a",
    primary: "#2563eb",
    "primary-foreground": "#ffffff",
    secondary: "#f0f0f1",
    "secondary-foreground": "#1a1a1a",
    muted: "#e8e8ea",
    "muted-foreground": "#6b7280",
    accent: "#e4e4e7",
    "accent-foreground": "#1a1a1a",
    destructive: "#ef4444",
    border: "#e2e2e5",
    input: "#d9d9dc",
    ring: "#2563eb",
    "chart-1": "#2563eb",
    "chart-2": "#10b981",
    "chart-3": "#f59e0b",
    "chart-4": "#8b5cf6",
    "chart-5": "#ec4899",
    sidebar: "#f0f0f2",
    "sidebar-foreground": "#1a1a1a",
    "sidebar-primary": "#2563eb",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#e4e4e7",
    "sidebar-accent-foreground": "#1a1a1a",
    "sidebar-border": "#e2e2e5",
    "sidebar-ring": "#2563eb",
  },
  dark: {
    background: "#181818",
    foreground: "#e4e4e4",
    card: "#1e1e1e",
    "card-foreground": "#e4e4e4",
    popover: "#1e1e1e",
    "popover-foreground": "#e4e4e4",
    primary: "#3b82f6",
    "primary-foreground": "#ffffff",
    secondary: "#222222",
    "secondary-foreground": "#e4e4e4",
    muted: "#252525",
    "muted-foreground": "#787878",
    accent: "#1e1e1e",
    "accent-foreground": "#e4e4e4",
    destructive: "#f85149",
    border: "#272727",
    input: "#1c1c1c",
    ring: "#3b82f6",
    "chart-1": "#3b82f6",
    "chart-2": "#34d399",
    "chart-3": "#fbbf24",
    "chart-4": "#a78bfa",
    "chart-5": "#f472b6",
    sidebar: "#141414",
    "sidebar-foreground": "#d0d0d0",
    "sidebar-primary": "#3b82f6",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#1e1e1e",
    "sidebar-accent-foreground": "#e4e4e4",
    "sidebar-border": "#1c1c1c",
    "sidebar-ring": "#3b82f6",
  },
}

// ── Tokyo Night (neon Tokyo at night; "Day" variant for light) ──────────────────

const tokyoNight: ColorTheme = {
  id: "tokyo-night",
  name: "Tokyo Night",
  description: "Downtown Tokyo after dark. Vivid neon on deep indigo.",
  group: "Built-in",
  radius: "0.625rem",
  light: {
    background: "#e1e2e7",
    foreground: "#343b59",
    card: "#eaebf1",
    "card-foreground": "#343b59",
    popover: "#eaebf1",
    "popover-foreground": "#343b59",
    primary: "#2e7de9",
    "primary-foreground": "#ffffff",
    secondary: "#d5d7e1",
    "secondary-foreground": "#343b59",
    muted: "#c9ccd9",
    "muted-foreground": "#5b628c",
    accent: "#c0c4d6",
    "accent-foreground": "#343b59",
    destructive: "#f52a65",
    border: "#d0d3de",
    input: "#c1c5d4",
    ring: "#2e7de9",
    "chart-1": "#2e7de9",
    "chart-2": "#587539",
    "chart-3": "#8c6c3e",
    "chart-4": "#f52a65",
    "chart-5": "#7847bd",
    sidebar: "#d7d9e2",
    "sidebar-foreground": "#343b59",
    "sidebar-primary": "#2e7de9",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#c9cdda",
    "sidebar-accent-foreground": "#343b59",
    "sidebar-border": "#c9ccd7",
    "sidebar-ring": "#2e7de9",
  },
  dark: {
    background: "#1a1b26",
    foreground: "#c0caf5",
    card: "#1e2030",
    "card-foreground": "#c0caf5",
    popover: "#1e2030",
    "popover-foreground": "#c0caf5",
    primary: "#7aa2f7",
    "primary-foreground": "#16161e",
    secondary: "#24283b",
    "secondary-foreground": "#c0caf5",
    muted: "#292e42",
    "muted-foreground": "#7982a9",
    accent: "#343a55",
    "accent-foreground": "#c0caf5",
    destructive: "#f7768e",
    border: "#252a40",
    input: "#2f344f",
    ring: "#7aa2f7",
    "chart-1": "#7aa2f7",
    "chart-2": "#9ece6a",
    "chart-3": "#e0af68",
    "chart-4": "#f7768e",
    "chart-5": "#bb9af7",
    sidebar: "#16161e",
    "sidebar-foreground": "#c0caf5",
    "sidebar-primary": "#7aa2f7",
    "sidebar-primary-foreground": "#16161e",
    "sidebar-accent": "#232841",
    "sidebar-accent-foreground": "#c0caf5",
    "sidebar-border": "#1d2133",
    "sidebar-ring": "#7aa2f7",
  },
}

/** All built-in themes, in display order. The first entry is the default. */
export const BUILT_IN_THEMES: ColorTheme[] = [
  jellybeans,
  macos,
  graphite,
  cursorAnysphere,
  nord,
  rosePine,
  catppuccin,
  tokyoNight,
  solarized,
]

/** The default theme id — matches the palette baked into `index.css`. */
export const DEFAULT_THEME_ID = jellybeans.id

/** Look up a theme by id, falling back to the default when unknown. */
export function getThemeById(id: string | null | undefined): ColorTheme {
  return BUILT_IN_THEMES.find((t) => t.id === id) ?? BUILT_IN_THEMES[0]
}
